// $Id$

/*===============================================================
* Current Version
* SKILLCHECK.INC - v1.0
* Updated 9/24/2005 6:52PM
*
* -- Revision v1.0 --
* Austin:
*  Created include file
===============================================================*/

use uo;
use os;

include ":attributes:attributes";
/*
function CheckStatAdvancement(mobile, stat_name)
	return 1;
endfunction

function CheckSkillAdvance(mobile, skill_name, award_difficulty, pass_chance, pass_success)
	return 1;
endfunction
*/